"""udalenie akkaunta gostya

Revision ID: 047f80b41582
Revises: 82bfe7e4704c
Create Date: 2026-08-22 11:52:19.704077

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "047f80b41582"
down_revision: str | Sequence[str] | None = "82bfe7e4704c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guests", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guests", "deleted_at")
    # ### end Alembic commands ###
