"""order item extras

Revision ID: 05f3fb1d0c6d
Revises: 6dcff92435b2
Create Date: 2026-08-18 22:19:55.563323

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05f3fb1d0c6d"
down_revision: str | Sequence[str] | None = "6dcff92435b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # У прошлых позиций добавок не было
    op.add_column(
        "order_items",
        sa.Column(
            "extras",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.alter_column("order_items", "extras", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "extras")
    # ### end Alembic commands ###
