"""ocenka zakaza

Revision ID: 14b1ea9592ab
Revises: f7e1f6251117
Create Date: 2026-08-24 10:48:02.947658

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14b1ea9592ab"
down_revision: str | Sequence[str] | None = "f7e1f6251117"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_feedback",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("guest_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
            name=op.f("fk_order_feedback_guest_id_guests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_feedback_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_order_feedback_restaurant_id_restaurants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_feedback")),
        sa.UniqueConstraint("order_id", name="uq_order_feedback_order"),
    )
    op.create_index(
        op.f("ix_order_feedback_guest_id"), "order_feedback", ["guest_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_feedback_order_id"), "order_feedback", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_feedback_restaurant_id"), "order_feedback", ["restaurant_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_feedback_tenant_id"), "order_feedback", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_feedback_tenant_id"), table_name="order_feedback")
    op.drop_index(op.f("ix_order_feedback_restaurant_id"), table_name="order_feedback")
    op.drop_index(op.f("ix_order_feedback_order_id"), table_name="order_feedback")
    op.drop_index(op.f("ix_order_feedback_guest_id"), table_name="order_feedback")
    op.drop_table("order_feedback")
    # ### end Alembic commands ###
