"""promo image size

Revision ID: 3183ddb96f22
Revises: 6aa3765f8661
Create Date: 2026-08-18 15:11:33.331567

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3183ddb96f22"
down_revision: str | Sequence[str] | None = "6aa3765f8661"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("image_width", sa.Integer(), nullable=True))
    op.add_column("promotions", sa.Column("image_height", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "image_height")
    op.drop_column("promotions", "image_width")
    # ### end Alembic commands ###
