"""cena tovara kassy

Revision ID: 3350e7a5736a
Revises: cfe0d02eb626
Create Date: 2026-08-28 19:13:25.087678

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3350e7a5736a"
down_revision: str | Sequence[str] | None = "cfe0d02eb626"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Номенклатура точки уже заведена: существующим строкам ставим ноль,
    # а умолчание убираем — цену дальше присылает плагин
    op.add_column(
        "iiko_products",
        sa.Column("price_kopecks", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("iiko_products", "price_kopecks", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("iiko_products", "price_kopecks")
    # ### end Alembic commands ###
