"""delivery hours and weekend minimum

Revision ID: 33c38241a9de
Revises: 37ac5f757b1a
Create Date: 2026-08-17 23:15:15.109693

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33c38241a9de"
down_revision: str | Sequence[str] | None = "37ac5f757b1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_zones", sa.Column("min_order_weekend_kopecks", sa.Integer(), nullable=True)
    )
    op.add_column("restaurants", sa.Column("delivery_opens_at", sa.Time(), nullable=True))
    op.add_column("restaurants", sa.Column("delivery_closes_at", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("restaurants", "delivery_closes_at")
    op.drop_column("restaurants", "delivery_opens_at")
    op.drop_column("delivery_zones", "min_order_weekend_kopecks")
    # ### end Alembic commands ###
