"""restaurant assortment

Revision ID: 37ac5f757b1a
Revises: 91c92e6c5b6d
Create Date: 2026-08-17 22:18:32.087921

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37ac5f757b1a"
down_revision: str | Sequence[str] | None = "91c92e6c5b6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dish_prices",
        sa.Column("is_available", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column("dish_prices", "is_available", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dish_prices", "is_available")
    # ### end Alembic commands ###
