"""promo restaurants many to many

Revision ID: 3b1083ae299e
Revises: 3183ddb96f22
Create Date: 2026-08-18 15:41:25.673644

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b1083ae299e"
down_revision: str | Sequence[str] | None = "3183ddb96f22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotion_restaurants",
        sa.Column("promotion_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.id"],
            name=op.f("fk_promotion_restaurants_promotion_id_promotions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_promotion_restaurants_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "promotion_id", "restaurant_id", name=op.f("pk_promotion_restaurants")
        ),
    )
    # Уже привязанные акции переезжают в новую таблицу, ничего не теряя
    op.execute(
        "INSERT INTO promotion_restaurants (promotion_id, restaurant_id) "
        "SELECT id, restaurant_id FROM promotions WHERE restaurant_id IS NOT NULL"
    )

    op.drop_index(op.f("ix_promotions_restaurant_id"), table_name="promotions")
    op.drop_constraint(
        op.f("fk_promotions_restaurant_id_restaurants"), "promotions", type_="foreignkey"
    )
    op.drop_column("promotions", "restaurant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promotions", sa.Column("restaurant_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_promotions_restaurant_id_restaurants"),
        "promotions",
        "restaurants",
        ["restaurant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_promotions_restaurant_id"), "promotions", ["restaurant_id"], unique=False
    )
    op.execute(
        "UPDATE promotions SET restaurant_id = link.restaurant_id FROM ("
        "SELECT DISTINCT ON (promotion_id) promotion_id, restaurant_id "
        "FROM promotion_restaurants) AS link WHERE promotions.id = link.promotion_id"
    )
    op.drop_table("promotion_restaurants")
    # ### end Alembic commands ###
