"""phone codes

Revision ID: 45cb5e48232d
Revises: 71c471018162
Create Date: 2026-08-15 00:27:06.277181

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '45cb5e48232d'
down_revision: str | Sequence[str] | None = '71c471018162'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_codes',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_codes'))
    )
    op.create_index(op.f('ix_phone_codes_tenant_id'), 'phone_codes', ['tenant_id'], unique=False)
    op.create_index('ix_phone_codes_tenant_phone', 'phone_codes', ['tenant_id', 'phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_codes_tenant_phone', table_name='phone_codes')
    op.drop_index(op.f('ix_phone_codes_tenant_id'), table_name='phone_codes')
    op.drop_table('phone_codes')
    # ### end Alembic commands ###
