"""preorder flag

Revision ID: 4f443200efac
Revises: baf7b9351282
Create Date: 2026-08-19 11:49:55.162794

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f443200efac"
down_revision: str | Sequence[str] | None = "baf7b9351282"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # По умолчанию заказы вне рабочих часов не принимаем
    op.add_column(
        "restaurants",
        sa.Column("preorder_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("restaurants", "preorder_enabled", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("restaurants", "preorder_enabled")
    # ### end Alembic commands ###
