"""restaurant pause

Revision ID: 51fb3a97881f
Revises: e3647b75383e
Create Date: 2026-08-17 09:15:16.314363

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51fb3a97881f"
down_revision: str | Sequence[str] | None = "e3647b75383e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurants",
        sa.Column("is_paused", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("restaurants", "is_paused", server_default=None)
    op.add_column("restaurants", sa.Column("pause_reason", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("restaurants", "pause_reason")
    op.drop_column("restaurants", "is_paused")
# ### end Alembic commands ###
