"""iiko po restoranam

Revision ID: 5f04b06cc12f
Revises: d41f53b09e94
Create Date: 2026-08-26 01:28:07.243337

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f04b06cc12f"
down_revision: str | Sequence[str] | None = "d41f53b09e94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iiko_links",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("dish_id", sa.Uuid(), nullable=True),
        sa.Column("extra_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("size_id", sa.String(length=64), nullable=True),
        sa.Column("modifier_group_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dish_id"],
            ["dishes.id"],
            name=op.f("fk_iiko_links_dish_id_dishes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extra_id"],
            ["dish_extras.id"],
            name=op.f("fk_iiko_links_extra_id_dish_extras"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_iiko_links_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iiko_links")),
        sa.UniqueConstraint(
            "tenant_id", "restaurant_id", "dish_id", name="uq_iiko_links_tenant_rest_dish"
        ),
        sa.UniqueConstraint(
            "tenant_id", "restaurant_id", "extra_id", name="uq_iiko_links_tenant_rest_extra"
        ),
    )
    op.create_index(op.f("ix_iiko_links_dish_id"), "iiko_links", ["dish_id"], unique=False)
    op.create_index(op.f("ix_iiko_links_extra_id"), "iiko_links", ["extra_id"], unique=False)
    op.create_index(op.f("ix_iiko_links_product_id"), "iiko_links", ["product_id"], unique=False)
    op.create_index(
        op.f("ix_iiko_links_restaurant_id"), "iiko_links", ["restaurant_id"], unique=False
    )
    op.create_index(op.f("ix_iiko_links_tenant_id"), "iiko_links", ["tenant_id"], unique=False)
    # Таблица не пустая: заполняем существующие заказы пустым объектом,
    # а умолчание тут же убираем — новые строки приходят со снимком из кода
    op.add_column(
        "orders",
        sa.Column(
            "address_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column("orders", "address_details", server_default=None)
    op.add_column("orders", sa.Column("delivery_minutes", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "delivery_minutes")
    op.drop_column("orders", "address_details")
    op.drop_index(op.f("ix_iiko_links_tenant_id"), table_name="iiko_links")
    op.drop_index(op.f("ix_iiko_links_restaurant_id"), table_name="iiko_links")
    op.drop_index(op.f("ix_iiko_links_product_id"), table_name="iiko_links")
    op.drop_index(op.f("ix_iiko_links_extra_id"), table_name="iiko_links")
    op.drop_index(op.f("ix_iiko_links_dish_id"), table_name="iiko_links")
    op.drop_table("iiko_links")
    # ### end Alembic commands ###
