"""promotion source url

Revision ID: 6aa3765f8661
Revises: bc8acba05160
Create Date: 2026-08-18 14:51:22.410362

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aa3765f8661"
down_revision: str | Sequence[str] | None = "bc8acba05160"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("source_url", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "source_url")
    # ### end Alembic commands ###
