"""dish extras

Revision ID: 6dcff92435b2
Revises: f06aa66518c1
Create Date: 2026-08-18 22:18:02.580549

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dcff92435b2"
down_revision: str | Sequence[str] | None = "f06aa66518c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dish_extras",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_kopecks", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dish_extras")),
    )
    op.create_index(
        op.f("ix_dish_extras_external_id"), "dish_extras", ["external_id"], unique=False
    )
    op.create_index(op.f("ix_dish_extras_tenant_id"), "dish_extras", ["tenant_id"], unique=False)
    op.create_table(
        "dish_extra_links",
        sa.Column("dish_id", sa.Uuid(), nullable=False),
        sa.Column("extra_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dish_id"],
            ["dishes.id"],
            name=op.f("fk_dish_extra_links_dish_id_dishes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extra_id"],
            ["dish_extras.id"],
            name=op.f("fk_dish_extra_links_extra_id_dish_extras"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("dish_id", "extra_id", name=op.f("pk_dish_extra_links")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dish_extra_links")
    op.drop_index(op.f("ix_dish_extras_tenant_id"), table_name="dish_extras")
    op.drop_index(op.f("ix_dish_extras_external_id"), table_name="dish_extras")
    op.drop_table("dish_extras")
    # ### end Alembic commands ###
