"""uvedomleniya: pravila, rassylki, scenarii

Revision ID: 715f02721a7f
Revises: 962df7bb08e4
Create Date: 2026-08-23 20:17:19.957991

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "715f02721a7f"
down_revision: str | Sequence[str] | None = "962df7bb08e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automations",
        sa.Column(
            "trigger",
            sa.Enum(
                "birthday",
                "inactive",
                "abandoned_cart",
                "points_expiring",
                name="triggerkind",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=240), nullable=False),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automations")),
        sa.UniqueConstraint("tenant_id", "trigger", name="uq_automations_trigger"),
    )
    op.create_index(op.f("ix_automations_tenant_id"), "automations", ["tenant_id"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=240), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "order",
                "marketing",
                name="notificationkind",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "scheduled",
                "sending",
                "sent",
                "cancelled",
                name="campaignstatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audience", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_count", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("opened_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(op.f("ix_campaigns_tenant_id"), "campaigns", ["tenant_id"], unique=False)
    op.create_table(
        "automation_deliveries",
        sa.Column("automation_id", sa.Uuid(), nullable=False),
        sa.Column("guest_id", sa.Uuid(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["automation_id"],
            ["automations.id"],
            name=op.f("fk_automation_deliveries_automation_id_automations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
            name=op.f("fk_automation_deliveries_guest_id_guests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_deliveries")),
    )
    op.create_index(
        op.f("ix_automation_deliveries_automation_id"),
        "automation_deliveries",
        ["automation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_deliveries_guest_id"),
        "automation_deliveries",
        ["guest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_deliveries_tenant_id"),
        "automation_deliveries",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "campaign_deliveries",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("guest_id", sa.Uuid(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_deliveries_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
            name=op.f("fk_campaign_deliveries_guest_id_guests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_deliveries")),
        sa.UniqueConstraint("campaign_id", "guest_id", name="uq_campaign_deliveries_guest"),
    )
    op.create_index(
        op.f("ix_campaign_deliveries_campaign_id"),
        "campaign_deliveries",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_deliveries_guest_id"), "campaign_deliveries", ["guest_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_deliveries_tenant_id"), "campaign_deliveries", ["tenant_id"], unique=False
    )
    op.create_table(
        "notification_hours",
        sa.Column("restaurant_id", sa.Uuid(), nullable=True),
        sa.Column("quiet_from", sa.Time(), nullable=False),
        sa.Column("quiet_to", sa.Time(), nullable=False),
        sa.Column("weekly_limit", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_notification_hours_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_hours")),
        sa.UniqueConstraint("tenant_id", "restaurant_id", name="uq_notification_hours_scope"),
    )
    op.create_index(
        op.f("ix_notification_hours_restaurant_id"),
        "notification_hours",
        ["restaurant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_hours_tenant_id"), "notification_hours", ["tenant_id"], unique=False
    )
    op.create_table(
        "notification_rules",
        sa.Column("restaurant_id", sa.Uuid(), nullable=True),
        sa.Column("event", sa.String(length=40), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=240), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_notification_rules_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_rules")),
        sa.UniqueConstraint(
            "tenant_id", "restaurant_id", "event", name="uq_notification_rules_scope"
        ),
    )
    op.create_index(
        op.f("ix_notification_rules_restaurant_id"),
        "notification_rules",
        ["restaurant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_rules_tenant_id"), "notification_rules", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_rules_tenant_id"), table_name="notification_rules")
    op.drop_index(op.f("ix_notification_rules_restaurant_id"), table_name="notification_rules")
    op.drop_table("notification_rules")
    op.drop_index(op.f("ix_notification_hours_tenant_id"), table_name="notification_hours")
    op.drop_index(op.f("ix_notification_hours_restaurant_id"), table_name="notification_hours")
    op.drop_table("notification_hours")
    op.drop_index(op.f("ix_campaign_deliveries_tenant_id"), table_name="campaign_deliveries")
    op.drop_index(op.f("ix_campaign_deliveries_guest_id"), table_name="campaign_deliveries")
    op.drop_index(op.f("ix_campaign_deliveries_campaign_id"), table_name="campaign_deliveries")
    op.drop_table("campaign_deliveries")
    op.drop_index(op.f("ix_automation_deliveries_tenant_id"), table_name="automation_deliveries")
    op.drop_index(op.f("ix_automation_deliveries_guest_id"), table_name="automation_deliveries")
    op.drop_index(
        op.f("ix_automation_deliveries_automation_id"), table_name="automation_deliveries"
    )
    op.drop_table("automation_deliveries")
    op.drop_index(op.f("ix_campaigns_tenant_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_automations_tenant_id"), table_name="automations")
    op.drop_table("automations")
    # ### end Alembic commands ###
