"""menu, guests, orders, reservations, loyalty

Revision ID: 71c471018162
Revises: 
Create Date: 2026-08-15 00:04:01.616581

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '71c471018162'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_cities_tenant_slug')
    )
    op.create_index(op.f('ix_cities_tenant_id'), 'cities', ['tenant_id'], unique=False)
    op.create_table('guests',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests')),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_guests_tenant_phone')
    )
    op.create_index(op.f('ix_guests_tenant_id'), 'guests', ['tenant_id'], unique=False)
    op.create_table('menu_categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_categories')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_menu_categories_tenant_slug')
    )
    op.create_index(op.f('ix_menu_categories_external_id'), 'menu_categories', ['external_id'], unique=False)
    op.create_index(op.f('ix_menu_categories_tenant_id'), 'menu_categories', ['tenant_id'], unique=False)
    op.create_table('devices',
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('push_token', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', name='deviceplatform', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_devices_guest_id_guests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('tenant_id', 'push_token', name='uq_devices_tenant_push_token')
    )
    op.create_index(op.f('ix_devices_guest_id'), 'devices', ['guest_id'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('dishes',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price_kopecks', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], name=op.f('fk_dishes_category_id_menu_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dishes'))
    )
    op.create_index(op.f('ix_dishes_category_id'), 'dishes', ['category_id'], unique=False)
    op.create_index(op.f('ix_dishes_external_id'), 'dishes', ['external_id'], unique=False)
    op.create_index(op.f('ix_dishes_tenant_id'), 'dishes', ['tenant_id'], unique=False)
    op.create_table('guest_addresses',
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('flat', sa.String(length=20), nullable=True),
    sa.Column('entrance', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('intercom', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_guest_addresses_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_guest_addresses_guest_id_guests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_addresses'))
    )
    op.create_index(op.f('ix_guest_addresses_city_id'), 'guest_addresses', ['city_id'], unique=False)
    op.create_index(op.f('ix_guest_addresses_guest_id'), 'guest_addresses', ['guest_id'], unique=False)
    op.create_index(op.f('ix_guest_addresses_tenant_id'), 'guest_addresses', ['tenant_id'], unique=False)
    op.create_table('loyalty_accounts',
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('tier_code', sa.String(length=30), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_spent_kopecks', sa.Integer(), nullable=False),
    sa.Column('tier_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_loyalty_accounts_guest_id_guests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_accounts')),
    sa.UniqueConstraint('tenant_id', 'guest_id', name='uq_loyalty_accounts_tenant_guest')
    )
    op.create_index(op.f('ix_loyalty_accounts_guest_id'), 'loyalty_accounts', ['guest_id'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_tenant_id'), 'loyalty_accounts', ['tenant_id'], unique=False)
    op.create_table('restaurants',
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('metro', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('has_delivery', sa.Boolean(), nullable=False),
    sa.Column('has_pickup', sa.Boolean(), nullable=False),
    sa.Column('has_dine_in', sa.Boolean(), nullable=False),
    sa.Column('delivery_price_kopecks', sa.Integer(), nullable=False),
    sa.Column('delivery_min_order_kopecks', sa.Integer(), nullable=False),
    sa.Column('free_delivery_from_kopecks', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_restaurants_city_id_cities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants'))
    )
    op.create_index(op.f('ix_restaurants_city_id'), 'restaurants', ['city_id'], unique=False)
    op.create_index(op.f('ix_restaurants_external_id'), 'restaurants', ['external_id'], unique=False)
    op.create_index(op.f('ix_restaurants_tenant_id'), 'restaurants', ['tenant_id'], unique=False)
    op.create_table('dish_prices',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('dish_id', sa.Uuid(), nullable=False),
    sa.Column('price_kopecks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_dish_prices_dish_id_dishes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_dish_prices_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dish_prices')),
    sa.UniqueConstraint('tenant_id', 'restaurant_id', 'dish_id', name='uq_dish_prices_tenant_restaurant_dish')
    )
    op.create_index(op.f('ix_dish_prices_dish_id'), 'dish_prices', ['dish_id'], unique=False)
    op.create_index(op.f('ix_dish_prices_restaurant_id'), 'dish_prices', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_dish_prices_tenant_id'), 'dish_prices', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('delivery', 'pickup', name='ordertype', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'accepted', 'cooking', 'ready', 'delivering', 'completed', 'cancelled', name='orderstatus', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('address_text', sa.String(length=400), nullable=True),
    sa.Column('address_latitude', sa.Float(), nullable=True),
    sa.Column('address_longitude', sa.Float(), nullable=True),
    sa.Column('delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('persons_count', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('subtotal_kopecks', sa.Integer(), nullable=False),
    sa.Column('delivery_kopecks', sa.Integer(), nullable=False),
    sa.Column('discount_kopecks', sa.Integer(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('total_kopecks', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('online_card', 'online_sbp', 'cash_on_delivery', 'card_on_delivery', name='paymentmethod', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('payment_status', sa.Enum('not_required', 'pending', 'succeeded', 'cancelled', 'refunded', name='paymentstatus', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('payment_external_id', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_orders_guest_id_guests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_orders_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('tenant_id', 'number', name='uq_orders_tenant_number')
    )
    op.create_index(op.f('ix_orders_external_id'), 'orders', ['external_id'], unique=False)
    op.create_index(op.f('ix_orders_guest_id'), 'orders', ['guest_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_external_id'), 'orders', ['payment_external_id'], unique=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('reservations',
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'seated', 'completed', 'cancelled', 'no_show', name='reservationstatus', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('table_number', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_reservations_guest_id_guests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_reservations_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index(op.f('ix_reservations_external_id'), 'reservations', ['external_id'], unique=False)
    op.create_index(op.f('ix_reservations_guest_id'), 'reservations', ['guest_id'], unique=False)
    op.create_index(op.f('ix_reservations_reserved_at'), 'reservations', ['reserved_at'], unique=False)
    op.create_index(op.f('ix_reservations_restaurant_id'), 'reservations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_tenant_id'), 'reservations', ['tenant_id'], unique=False)
    op.create_table('stop_list',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('dish_id', sa.Uuid(), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_stop_list_dish_id_dishes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_stop_list_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stop_list')),
    sa.UniqueConstraint('tenant_id', 'restaurant_id', 'dish_id', name='uq_stop_list_tenant_restaurant_dish')
    )
    op.create_index(op.f('ix_stop_list_dish_id'), 'stop_list', ['dish_id'], unique=False)
    op.create_index(op.f('ix_stop_list_restaurant_id'), 'stop_list', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_stop_list_tenant_id'), 'stop_list', ['tenant_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.Enum('welcome', 'earn', 'spend', 'refund', 'birthday', 'expire', 'manual', name='loyaltyoperation', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], name=op.f('fk_loyalty_transactions_account_id_loyalty_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_loyalty_transactions_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_transactions'))
    )
    op.create_index(op.f('ix_loyalty_transactions_account_id'), 'loyalty_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_expires_at'), 'loyalty_transactions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_order_id'), 'loyalty_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_tenant_id'), 'loyalty_transactions', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('dish_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_price_kopecks', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_kopecks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_order_items_dish_id_dishes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_dish_id'), 'order_items', ['dish_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_tenant_id'), 'order_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_tenant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_dish_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_loyalty_transactions_tenant_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_order_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_expires_at'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_account_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_stop_list_tenant_id'), table_name='stop_list')
    op.drop_index(op.f('ix_stop_list_restaurant_id'), table_name='stop_list')
    op.drop_index(op.f('ix_stop_list_dish_id'), table_name='stop_list')
    op.drop_table('stop_list')
    op.drop_index(op.f('ix_reservations_tenant_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_restaurant_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reserved_at'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_guest_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_external_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_external_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_guest_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dish_prices_tenant_id'), table_name='dish_prices')
    op.drop_index(op.f('ix_dish_prices_restaurant_id'), table_name='dish_prices')
    op.drop_index(op.f('ix_dish_prices_dish_id'), table_name='dish_prices')
    op.drop_table('dish_prices')
    op.drop_index(op.f('ix_restaurants_tenant_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_external_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_city_id'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_loyalty_accounts_tenant_id'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_guest_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index(op.f('ix_guest_addresses_tenant_id'), table_name='guest_addresses')
    op.drop_index(op.f('ix_guest_addresses_guest_id'), table_name='guest_addresses')
    op.drop_index(op.f('ix_guest_addresses_city_id'), table_name='guest_addresses')
    op.drop_table('guest_addresses')
    op.drop_index(op.f('ix_dishes_tenant_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_external_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_category_id'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_guest_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_menu_categories_tenant_id'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_external_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_guests_tenant_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_cities_tenant_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
