"""vid tovara kassy

Revision ID: 7b8f1397c3bd
Revises: 5f04b06cc12f
Create Date: 2026-08-26 12:26:58.383326

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b8f1397c3bd"
down_revision: str | Sequence[str] | None = "5f04b06cc12f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("iiko_products", sa.Column("product_type", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("iiko_products", "product_type")
    # ### end Alembic commands ###
