"""galereya restoranov

Revision ID: 82bfe7e4704c
Revises: 4f443200efac
Create Date: 2026-08-21 20:10:16.240151

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82bfe7e4704c"
down_revision: str | Sequence[str] | None = "4f443200efac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurant_photos",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_restaurant_photos_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restaurant_photos")),
    )
    op.create_index(
        op.f("ix_restaurant_photos_restaurant_id"),
        "restaurant_photos",
        ["restaurant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restaurant_photos_tenant_id"), "restaurant_photos", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_restaurant_photos_tenant_id"), table_name="restaurant_photos")
    op.drop_index(op.f("ix_restaurant_photos_restaurant_id"), table_name="restaurant_photos")
    op.drop_table("restaurant_photos")
    # ### end Alembic commands ###
