"""order item photo

Revision ID: 8547073f6c76
Revises: 96c3067a30fc
Create Date: 2026-08-17 13:24:05.771827

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8547073f6c76"
down_revision: str | Sequence[str] | None = "96c3067a30fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_items", sa.Column("image_url", sa.String(length=500), nullable=True))

    # Старым заказам подставляем текущее фото блюда — лучше, чем пустое место
    op.execute(
        """
        UPDATE order_items
        SET image_url = dishes.image_url
        FROM dishes
        WHERE order_items.dish_id = dishes.id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "image_url")
    # ### end Alembic commands ###
