"""tip_zakaza_v_pravilah_uvedomlenij

Revision ID: 88098af8c760
Revises: f7e61afea942
Create Date: 2026-09-03 12:28:36.270627

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88098af8c760"
down_revision: str | Sequence[str] | None = "f7e61afea942"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_rules",
        sa.Column(
            "order_type",
            sa.Enum(
                "delivery",
                "pickup",
                name="ordertype",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=True,
        ),
    )
    op.drop_constraint(op.f("uq_notification_rules_scope"), "notification_rules", type_="unique")

    # Уникальность держим индексом по выражениям, а не ограничением: в Postgres
    # NULL друг другу не равны, поэтому сетевое правило (ресторан не задан) или
    # общее по способу получения (тип не задан) заводились бы дважды. Готовый
    # UNIQUE NULLS NOT DISTINCT есть только с пятнадцатой версии, а на сервере
    # четырнадцатая — обходимся COALESCE
    op.create_index(
        "uq_notification_rules_scope",
        "notification_rules",
        [
            sa.text("tenant_id"),
            sa.text("coalesce(restaurant_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
            sa.text("event"),
            sa.text("coalesce(order_type, '')"),
        ],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_notification_rules_scope", table_name="notification_rules")
    op.create_unique_constraint(
        op.f("uq_notification_rules_scope"),
        "notification_rules",
        ["tenant_id", "restaurant_id", "event"],
    )
    op.drop_column("notification_rules", "order_type")
    # ### end Alembic commands ###
