"""delivery zones

Revision ID: 91c92e6c5b6d
Revises: 8547073f6c76
Create Date: 2026-08-17 22:15:19.424939

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91c92e6c5b6d"
down_revision: str | Sequence[str] | None = "8547073f6c76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_zones",
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("outline", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column("delivery_price_kopecks", sa.Integer(), nullable=False),
        sa.Column("min_order_kopecks", sa.Integer(), nullable=False),
        sa.Column("free_delivery_from_kopecks", sa.Integer(), nullable=True),
        sa.Column("delivery_minutes", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_delivery_zones_city_id_cities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_delivery_zones_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_zones")),
    )
    op.create_index(op.f("ix_delivery_zones_city_id"), "delivery_zones", ["city_id"], unique=False)
    op.create_index(
        op.f("ix_delivery_zones_external_id"), "delivery_zones", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_zones_restaurant_id"), "delivery_zones", ["restaurant_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_zones_tenant_id"), "delivery_zones", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_zones_tenant_id"), table_name="delivery_zones")
    op.drop_index(op.f("ix_delivery_zones_restaurant_id"), table_name="delivery_zones")
    op.drop_index(op.f("ix_delivery_zones_external_id"), table_name="delivery_zones")
    op.drop_index(op.f("ix_delivery_zones_city_id"), table_name="delivery_zones")
    op.drop_table("delivery_zones")
    # ### end Alembic commands ###
