"""popular shelf categories

Revision ID: 92adebc8f269
Revises: b15706cb11d4
Create Date: 2026-08-18 18:08:03.855156

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92adebc8f269"
down_revision: str | Sequence[str] | None = "b15706cb11d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Таблица уже заполнена: по умолчанию раздел на полке показываем
    op.add_column(
        "menu_categories",
        sa.Column("show_in_popular", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column("menu_categories", "show_in_popular", server_default=None)

    # Соусы, напитки и детское меню на полке «Часто заказывают» не нужны
    op.execute(
        "UPDATE menu_categories SET show_in_popular = false "
        "WHERE slug IN ('salse', 'soki', 'kids')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_categories", "show_in_popular")
    # ### end Alembic commands ###
