"""nutrition

Revision ID: 96087df7ed08
Revises: fb2c841311c5
Create Date: 2026-08-16 15:39:56.949199

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96087df7ed08"
down_revision: str | Sequence[str] | None = "fb2c841311c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dishes", sa.Column("proteins_g", sa.Float(), nullable=True))
    op.add_column("dishes", sa.Column("fats_g", sa.Float(), nullable=True))
    op.add_column("dishes", sa.Column("carbs_g", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dishes", "carbs_g")
    op.drop_column("dishes", "fats_g")
    op.drop_column("dishes", "proteins_g")
    # ### end Alembic commands ###
