"""otpechatki kartinok

Revision ID: 962df7bb08e4
Revises: 047f80b41582
Create Date: 2026-08-22 23:19:49.228020

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "962df7bb08e4"
down_revision: str | Sequence[str] | None = "047f80b41582"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dishes", sa.Column("image_blurhash", sa.String(length=40), nullable=True))
    op.add_column(
        "menu_categories", sa.Column("image_blurhash", sa.String(length=40), nullable=True)
    )
    op.add_column("promotions", sa.Column("image_blurhash", sa.String(length=40), nullable=True))
    op.add_column("restaurants", sa.Column("image_blurhash", sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("restaurants", "image_blurhash")
    op.drop_column("promotions", "image_blurhash")
    op.drop_column("menu_categories", "image_blurhash")
    op.drop_column("dishes", "image_blurhash")
    # ### end Alembic commands ###
