"""short card number

Revision ID: 96c3067a30fc
Revises: c8c408bb0648
Create Date: 2026-08-17 13:17:56.298998

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96c3067a30fc"
down_revision: str | Sequence[str] | None = "c8c408bb0648"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Тринадцатизначный номер оказался неудобен вслух: переходим на шесть цифр,
    # а штрихкод для сканера собираем из них на лету
    op.execute("UPDATE loyalty_accounts SET card_number = ''")
    op.alter_column(
        "loyalty_accounts",
        "card_number",
        existing_type=sa.VARCHAR(length=13),
        type_=sa.String(length=6),
        existing_nullable=False,
    )

    from app.core.security import generate_card_number

    bind = op.get_bind()
    issued: set[str] = set()
    for (account_id,) in bind.execute(sa.text("SELECT id FROM loyalty_accounts")).all():
        number = generate_card_number()
        while number in issued:
            number = generate_card_number()
        issued.add(number)
        bind.execute(
            sa.text("UPDATE loyalty_accounts SET card_number = :number WHERE id = :id"),
            {"number": number, "id": account_id},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "loyalty_accounts",
        "card_number",
        existing_type=sa.String(length=6),
        type_=sa.VARCHAR(length=13),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
