"""staff audit log

Revision ID: aca9285895c0
Revises: a1c7f3b90e42
Create Date: 2026-09-04 02:06:55.946388

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aca9285895c0"
down_revision: str | Sequence[str] | None = "a1c7f3b90e42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_audit_log",
        sa.Column("staff_id", sa.Uuid(), nullable=True),
        sa.Column("staff_name", sa.String(length=120), nullable=False),
        sa.Column(
            "staff_role",
            sa.Enum(
                "owner",
                "network_manager",
                "delivery_operator",
                "marketing",
                "courier",
                "restaurant",
                name="staffrole",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=300), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff_users.id"],
            name=op.f("fk_staff_audit_log_staff_id_staff_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_audit_log")),
    )
    op.create_index(
        op.f("ix_staff_audit_log_created_at"), "staff_audit_log", ["created_at"], unique=False
    )
    op.create_index(
        "ix_staff_audit_log_tenant_created",
        "staff_audit_log",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_staff_audit_log_tenant_id"), "staff_audit_log", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_staff_audit_log_tenant_section",
        "staff_audit_log",
        ["tenant_id", "section"],
        unique=False,
    )
    op.create_index(
        "ix_staff_audit_log_tenant_staff",
        "staff_audit_log",
        ["tenant_id", "staff_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_staff_audit_log_tenant_staff", table_name="staff_audit_log")
    op.drop_index("ix_staff_audit_log_tenant_section", table_name="staff_audit_log")
    op.drop_index(op.f("ix_staff_audit_log_tenant_id"), table_name="staff_audit_log")
    op.drop_index("ix_staff_audit_log_tenant_created", table_name="staff_audit_log")
    op.drop_index(op.f("ix_staff_audit_log_created_at"), table_name="staff_audit_log")
    op.drop_table("staff_audit_log")
    # ### end Alembic commands ###
