"""sync changes

Revision ID: b15706cb11d4
Revises: 7fd8808f55fa
Create Date: 2026-08-18 16:53:18.372803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b15706cb11d4"
down_revision: str | Sequence[str] | None = "7fd8808f55fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_changes",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=400), nullable=False),
        sa.Column("group", sa.String(length=120), nullable=True),
        sa.Column("external_id", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["sync_runs.id"],
            name=op.f("fk_sync_changes_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_changes")),
    )
    op.create_index(op.f("ix_sync_changes_run_id"), "sync_changes", ["run_id"], unique=False)
    op.create_index(op.f("ix_sync_changes_tenant_id"), "sync_changes", ["tenant_id"], unique=False)
    op.add_column("sync_runs", sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True))
    # В таблице уже есть строки прошлых запусков — им ставим ноль
    op.add_column(
        "sync_runs", sa.Column("unchanged", sa.Integer(), nullable=False, server_default="0")
    )
    op.alter_column("sync_runs", "unchanged", server_default=None)
    op.drop_column("sync_runs", "skipped")
    op.drop_column("sync_runs", "replace_existing")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_runs",
        sa.Column("replace_existing", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "sync_runs", sa.Column("skipped", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_column("sync_runs", "unchanged")
    op.drop_column("sync_runs", "applied_at")
    op.drop_index(op.f("ix_sync_changes_tenant_id"), table_name="sync_changes")
    op.drop_index(op.f("ix_sync_changes_run_id"), table_name="sync_changes")
    op.drop_table("sync_changes")
    # ### end Alembic commands ###
