"""city suggest regions and address locality

Revision ID: b32aaef595bd
Revises: b77da332cd8d
Create Date: 2026-08-16 23:46:53.826813

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b32aaef595bd"
down_revision: str | Sequence[str] | None = "b77da332cd8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cities",
        sa.Column(
            "suggest_regions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.alter_column("cities", "suggest_regions", server_default=None)
    op.add_column("guest_addresses", sa.Column("locality", sa.String(length=120), nullable=True))

    # Коды КЛАДР: 78 — Петербург, 47 — Ленинградская область (Кудрово, Мурино)
    op.execute(
        """
        UPDATE cities
        SET suggest_regions = '["78", "47"]'::jsonb
        WHERE slug = 'spb'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guest_addresses", "locality")
    op.drop_column("cities", "suggest_regions")
    # ### end Alembic commands ###
