"""soglasie na reklamu

Revision ID: b4c47de36857
Revises: 715f02721a7f
Create Date: 2026-08-23 23:18:41.379717

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4c47de36857"
down_revision: str | Sequence[str] | None = "715f02721a7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guests",
        sa.Column("marketing_opt_in", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column("guests", "marketing_opt_in", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guests", "marketing_opt_in")
    # ### end Alembic commands ###
