"""address standardization fields

Revision ID: b77da332cd8d
Revises: bf0162b21d56
Create Date: 2026-08-16 23:33:12.901903

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b77da332cd8d"
down_revision: str | Sequence[str] | None = "bf0162b21d56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guest_addresses", sa.Column("fias_id", sa.String(length=40), nullable=True))
    op.add_column("guest_addresses", sa.Column("postal_code", sa.String(length=10), nullable=True))
    op.add_column(
        "guest_addresses", sa.Column("city_district", sa.String(length=120), nullable=True)
    )
    op.add_column("guest_addresses", sa.Column("metro", sa.String(length=120), nullable=True))
    op.add_column("guest_addresses", sa.Column("geo_precision", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guest_addresses", "geo_precision")
    op.drop_column("guest_addresses", "metro")
    op.drop_column("guest_addresses", "city_district")
    op.drop_column("guest_addresses", "postal_code")
    op.drop_column("guest_addresses", "fias_id")
    # ### end Alembic commands ###
