"""category extras

Revision ID: baf7b9351282
Revises: 05f3fb1d0c6d
Create Date: 2026-08-18 23:29:09.853017

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baf7b9351282"
down_revision: str | Sequence[str] | None = "05f3fb1d0c6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_extra_links",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("extra_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["menu_categories.id"],
            name=op.f("fk_category_extra_links_category_id_menu_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extra_id"],
            ["dish_extras.id"],
            name=op.f("fk_category_extra_links_extra_id_dish_extras"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("category_id", "extra_id", name=op.f("pk_category_extra_links")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category_extra_links")
    # ### end Alembic commands ###
