"""promotion external id

Revision ID: bc8acba05160
Revises: d0f2c98390d6
Create Date: 2026-08-18 14:38:18.131751

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc8acba05160"
down_revision: str | Sequence[str] | None = "d0f2c98390d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("external_id", sa.String(length=64), nullable=True))
    op.add_column("promotions", sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_promotions_external_id"), "promotions", ["external_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promotions_external_id"), table_name="promotions")
    op.drop_column("promotions", "synced_at")
    op.drop_column("promotions", "external_id")
    # ### end Alembic commands ###
