"""guest gender and address building

Revision ID: bf0162b21d56
Revises: 96087df7ed08
Create Date: 2026-08-16 21:56:24.981534

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf0162b21d56"
down_revision: str | Sequence[str] | None = "96087df7ed08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guest_addresses", sa.Column("building", sa.String(length=20), nullable=True))
    op.add_column(
        "guests",
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                name="gender",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guests", "gender")
    op.drop_column("guest_addresses", "building")
    # ### end Alembic commands ###
