"""promo codes and change

Revision ID: bfcd54fc8993
Revises: 92adebc8f269
Create Date: 2026-08-18 20:19:54.152257

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfcd54fc8993"
down_revision: str | Sequence[str] | None = "92adebc8f269"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promo_codes",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "percent",
                "fixed",
                "free_delivery",
                name="promocodekind",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("max_discount_kopecks", sa.Integer(), nullable=True),
        sa.Column("min_order_kopecks", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("per_guest_limit", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_codes")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_promo_codes_tenant_code"),
    )
    op.create_index(op.f("ix_promo_codes_code"), "promo_codes", ["code"], unique=False)
    op.create_index(op.f("ix_promo_codes_tenant_id"), "promo_codes", ["tenant_id"], unique=False)
    op.add_column("orders", sa.Column("change_from_kopecks", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("promo_code", sa.String(length=32), nullable=True))
    # В таблице уже есть заказы: у них скидки по промокоду не было
    op.add_column(
        "orders",
        sa.Column("promo_discount_kopecks", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("orders", "promo_discount_kopecks", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "promo_discount_kopecks")
    op.drop_column("orders", "promo_code")
    op.drop_column("orders", "change_from_kopecks")
    op.drop_index(op.f("ix_promo_codes_tenant_id"), table_name="promo_codes")
    op.drop_index(op.f("ix_promo_codes_code"), table_name="promo_codes")
    op.drop_table("promo_codes")
    # ### end Alembic commands ###
