"""loyalty card number

Revision ID: c8c408bb0648
Revises: 51fb3a97881f
Create Date: 2026-08-17 13:05:58.083252

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8c408bb0648"
down_revision: str | Sequence[str] | None = "51fb3a97881f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loyalty_accounts",
        sa.Column("card_number", sa.String(length=13), nullable=False, server_default=""),
    )
    op.alter_column("loyalty_accounts", "card_number", server_default=None)

    # Существующим гостям выдаём карты тем же генератором, что и новым
    from app.core.security import generate_card_number

    bind = op.get_bind()
    issued: set[str] = set()
    for (account_id,) in bind.execute(
        sa.text("SELECT id FROM loyalty_accounts WHERE card_number = ''")
    ).all():
        number = generate_card_number()
        while number in issued:
            number = generate_card_number()
        issued.add(number)
        bind.execute(
            sa.text("UPDATE loyalty_accounts SET card_number = :number WHERE id = :id"),
            {"number": number, "id": account_id},
        )
    op.create_index(
        op.f("ix_loyalty_accounts_card_number"), "loyalty_accounts", ["card_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_loyalty_accounts_card_number"), table_name="loyalty_accounts")
    op.drop_column("loyalty_accounts", "card_number")
    # ### end Alembic commands ###
