"""derevo menu v baze

Revision ID: cfe0d02eb626
Revises: c31d7a9f0b54
Create Date: 2026-08-28 18:50:50.360380

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfe0d02eb626"
down_revision: str | Sequence[str] | None = "c31d7a9f0b54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iiko_menu_setup",
        sa.Column("deny_markers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extra_group_paths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("keep_unknown_groups", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iiko_menu_setup")),
        sa.UniqueConstraint("tenant_id", name="uq_iiko_menu_setup_tenant"),
    )
    op.create_index(
        op.f("ix_iiko_menu_setup_tenant_id"), "iiko_menu_setup", ["tenant_id"], unique=False
    )
    # Таблица не пустая: существующим категориям ставим пустой список,
    # а умолчание тут же убираем — дальше значение приходит из кода
    op.add_column(
        "menu_categories",
        sa.Column(
            "iiko_group_paths",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column("menu_categories", "iiko_group_paths", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_categories", "iiko_group_paths")
    op.drop_index(op.f("ix_iiko_menu_setup_tenant_id"), table_name="iiko_menu_setup")
    op.drop_table("iiko_menu_setup")
    # ### end Alembic commands ###
