"""promotion in menu flag

Revision ID: d0f2c98390d6
Revises: 33c38241a9de
Create Date: 2026-08-18 14:37:16.993670

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0f2c98390d6"
down_revision: str | Sequence[str] | None = "33c38241a9de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promotions",
        sa.Column("show_in_menu", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("promotions", "show_in_menu", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "show_in_menu")
    # ### end Alembic commands ###
