"""iiko bridge

Revision ID: d41f53b09e94
Revises: 14b1ea9592ab
Create Date: 2026-08-26 01:03:51.320723

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d41f53b09e94"
down_revision: str | Sequence[str] | None = "14b1ea9592ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iiko_bridges",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("secret", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("plugin_version", sa.String(length=32), nullable=True),
        sa.Column("terminal_name", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_iiko_bridges_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iiko_bridges")),
        sa.UniqueConstraint("tenant_id", "restaurant_id", name="uq_iiko_bridges_tenant_restaurant"),
    )
    op.create_index(
        op.f("ix_iiko_bridges_restaurant_id"), "iiko_bridges", ["restaurant_id"], unique=False
    )
    op.create_index(op.f("ix_iiko_bridges_tenant_id"), "iiko_bridges", ["tenant_id"], unique=False)
    op.create_table(
        "iiko_products",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=True),
        sa.Column("group_name", sa.String(length=160), nullable=True),
        sa.Column("group_path", sa.String(length=400), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("measure_unit", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("has_sizes", sa.Boolean(), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_iiko_products_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iiko_products")),
        sa.UniqueConstraint(
            "tenant_id", "restaurant_id", "product_id", name="uq_iiko_products_tenant_rest_product"
        ),
    )
    op.create_index(
        op.f("ix_iiko_products_product_id"), "iiko_products", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_iiko_products_restaurant_id"), "iiko_products", ["restaurant_id"], unique=False
    )
    op.create_index(
        op.f("ix_iiko_products_tenant_id"), "iiko_products", ["tenant_id"], unique=False
    )
    op.create_table(
        "iiko_order_handoffs",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "accepted",
                "failed",
                "skipped",
                name="iikohandoffstatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("iiko_order_id", sa.String(length=64), nullable=True),
        sa.Column("iiko_order_number", sa.String(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("missing_products", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_iiko_order_handoffs_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_iiko_order_handoffs_restaurant_id_restaurants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iiko_order_handoffs")),
        sa.UniqueConstraint("tenant_id", "order_id", name="uq_iiko_handoffs_tenant_order"),
    )
    op.create_index(
        op.f("ix_iiko_order_handoffs_order_id"), "iiko_order_handoffs", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_iiko_order_handoffs_restaurant_id"),
        "iiko_order_handoffs",
        ["restaurant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_iiko_order_handoffs_status"), "iiko_order_handoffs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_iiko_order_handoffs_tenant_id"), "iiko_order_handoffs", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_iiko_order_handoffs_tenant_id"), table_name="iiko_order_handoffs")
    op.drop_index(op.f("ix_iiko_order_handoffs_status"), table_name="iiko_order_handoffs")
    op.drop_index(op.f("ix_iiko_order_handoffs_restaurant_id"), table_name="iiko_order_handoffs")
    op.drop_index(op.f("ix_iiko_order_handoffs_order_id"), table_name="iiko_order_handoffs")
    op.drop_table("iiko_order_handoffs")
    op.drop_index(op.f("ix_iiko_products_tenant_id"), table_name="iiko_products")
    op.drop_index(op.f("ix_iiko_products_restaurant_id"), table_name="iiko_products")
    op.drop_index(op.f("ix_iiko_products_product_id"), table_name="iiko_products")
    op.drop_table("iiko_products")
    op.drop_index(op.f("ix_iiko_bridges_tenant_id"), table_name="iiko_bridges")
    op.drop_index(op.f("ix_iiko_bridges_restaurant_id"), table_name="iiko_bridges")
    op.drop_table("iiko_bridges")
    # ### end Alembic commands ###
