"""own address directory

Revision ID: e3647b75383e
Revises: b32aaef595bd
Create Date: 2026-08-17 00:03:39.313595

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3647b75383e"
down_revision: str | Sequence[str] | None = "b32aaef595bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_addresses",
        sa.Column("region_code", sa.String(length=2), nullable=False),
        sa.Column("locality", sa.String(length=120), nullable=True),
        sa.Column("street", sa.String(length=200), nullable=False),
        sa.Column("house", sa.String(length=20), nullable=False),
        sa.Column("building", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=260), nullable=False),
        sa.Column("subtitle", sa.String(length=260), nullable=False),
        sa.Column("search_text", sa.String(length=400), nullable=False),
        sa.Column("fias_id", sa.String(length=40), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("city_district", sa.String(length=120), nullable=True),
        sa.Column("metro", sa.String(length=120), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("geo_precision", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geo_addresses")),
        sa.UniqueConstraint("fias_id", name="uq_geo_addresses_fias"),
    )
    op.create_index(
        op.f("ix_geo_addresses_region_code"), "geo_addresses", ["region_code"], unique=False
    )
    # ### end Alembic commands ###

    # Поиск идёт по кускам слов («невс», «столичн»), обычный индекс тут бесполезен.
    # Триграммы умеют LIKE с любой стороны и держат поиск быстрым на миллионах строк
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX ix_geo_addresses_search ON geo_addresses USING gin (search_text gin_trgm_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_geo_addresses_search")
    op.drop_index(op.f("ix_geo_addresses_region_code"), table_name="geo_addresses")
    op.drop_table("geo_addresses")
    # ### end Alembic commands ###
