"""cutlery price

Revision ID: f06aa66518c1
Revises: bfcd54fc8993
Create Date: 2026-08-18 20:52:01.521550

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f06aa66518c1"
down_revision: str | Sequence[str] | None = "bfcd54fc8993"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # У прошлых заказов приборов не было
    op.add_column(
        "orders", sa.Column("cutlery_kopecks", sa.Integer(), nullable=False, server_default="0")
    )
    op.alter_column("orders", "cutlery_kopecks", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "cutlery_kopecks")
    # ### end Alembic commands ###
