"""sled korziny

Revision ID: f7e1f6251117
Revises: b4c47de36857
Create Date: 2026-08-24 10:20:49.054461

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7e1f6251117"
down_revision: str | Sequence[str] | None = "b4c47de36857"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart_snapshots",
        sa.Column("guest_id", sa.Uuid(), nullable=False),
        sa.Column("positions", sa.Integer(), nullable=False),
        sa.Column("total_kopecks", sa.Integer(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reminded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
            name=op.f("fk_cart_snapshots_guest_id_guests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_snapshots")),
        sa.UniqueConstraint("tenant_id", "guest_id", name="uq_cart_snapshots_guest"),
    )
    op.create_index(
        op.f("ix_cart_snapshots_guest_id"), "cart_snapshots", ["guest_id"], unique=False
    )
    op.create_index(
        op.f("ix_cart_snapshots_tenant_id"), "cart_snapshots", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cart_snapshots_tenant_id"), table_name="cart_snapshots")
    op.drop_index(op.f("ix_cart_snapshots_guest_id"), table_name="cart_snapshots")
    op.drop_table("cart_snapshots")
    # ### end Alembic commands ###
