"""dish badges

Revision ID: fb2c841311c5
Revises: 077bcb21ce81
Create Date: 2026-08-16 00:45:46.994666

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb2c841311c5"
down_revision: str | Sequence[str] | None = "077bcb21ce81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dishes",
        sa.Column("is_spicy", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("dishes", "is_spicy", server_default=None)
    op.add_column(
        "dishes",
        sa.Column("is_vegetarian", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("dishes", "is_vegetarian", server_default=None)
    op.add_column(
        "dishes",
        sa.Column("is_new", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("dishes", "is_new", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dishes", "is_new")
    op.drop_column("dishes", "is_vegetarian")
    op.drop_column("dishes", "is_spicy")
    # ### end Alembic commands ###
