/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить код подтверждения */
        post: operations["request_code_api_v1_auth_request_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить код и войти */
        post: operations["verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить пару токенов */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего гостя */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить данные гостя */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Адреса доставки гостя */
        get: operations["list_addresses_api_v1_addresses_get"];
        put?: never;
        /** Добавить адрес */
        post: operations["add_address_api_v1_addresses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses/{address_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить адрес */
        delete: operations["delete_address_api_v1_addresses__address_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Города присутствия сети */
        get: operations["list_cities_api_v1_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Рестораны, при желании одного города */
        get: operations["list_restaurants_api_v1_restaurants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог блюд по категориям */
        get: operations["get_menu_api_v1_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сколько баллов можно списать с этой суммы */
        get: operations["limits_api_v1_orders_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Заказы гостя */
        get: operations["index_api_v1_orders_get"];
        put?: never;
        /** Оформить заказ */
        post: operations["create_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка заказа */
        get: operations["show_api_v1_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Свободное время на дату */
        get: operations["slots_api_v1_reservations_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Брони гостя */
        get: operations["index_api_v1_reservations_get"];
        put?: never;
        /** Забронировать стол */
        post: operations["create_api_v1_reservations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{reservation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить бронь */
        post: operations["cancel_api_v1_reservations__reservation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Действующие акции */
        get: operations["promotions_api_v1_promotions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход сотрудника */
        post: operations["login_api_v1_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий сотрудник */
        get: operations["me_api_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить фотографию */
        post: operations["upload_api_v1_admin_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Категории меню */
        get: operations["categories_api_v1_admin_categories_get"];
        put?: never;
        /** Создать категорию */
        post: operations["create_category_api_v1_admin_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить категорию */
        delete: operations["delete_category_api_v1_admin_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Изменить категорию */
        patch: operations["update_category_api_v1_admin_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/dishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Блюда */
        get: operations["dishes_api_v1_admin_dishes_get"];
        put?: never;
        /** Создать блюдо */
        post: operations["create_dish_api_v1_admin_dishes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dishes/{dish_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить блюдо */
        delete: operations["delete_dish_api_v1_admin_dishes__dish_id__delete"];
        options?: never;
        head?: never;
        /** Изменить блюдо */
        patch: operations["update_dish_api_v1_admin_dishes__dish_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/stop-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Что сейчас в стоп-листе */
        get: operations["stop_list_api_v1_admin_stop_list_get"];
        put?: never;
        /** Поставить в стоп-лист */
        post: operations["add_to_stop_list_api_v1_admin_stop_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stop-list/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Убрать из стоп-листа */
        delete: operations["remove_from_stop_list_api_v1_admin_stop_list__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Заказы сети */
        get: operations["orders_api_v1_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Сменить статус заказа */
        patch: operations["set_order_status_api_v1_admin_orders__order_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Брони сети */
        get: operations["reservations_api_v1_admin_reservations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/{reservation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Сменить статус брони */
        patch: operations["set_reservation_status_api_v1_admin_reservations__reservation_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все акции */
        get: operations["promotions_api_v1_admin_promotions_get"];
        put?: never;
        /** Создать акцию */
        post: operations["create_promotion_api_v1_admin_promotions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/promotions/{promotion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить акцию */
        delete: operations["delete_promotion_api_v1_admin_promotions__promotion_id__delete"];
        options?: never;
        head?: never;
        /** Изменить акцию */
        patch: operations["update_promotion_api_v1_admin_promotions__promotion_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressCreate */
        AddressCreate: {
            /**
             * City Id
             * Format: uuid
             */
            city_id: string;
            /** Street */
            street: string;
            /** House */
            house: string;
            /** Title */
            title?: string | null;
            /** Flat */
            flat?: string | null;
            /** Entrance */
            entrance?: string | null;
            /** Floor */
            floor?: string | null;
            /** Intercom */
            intercom?: string | null;
            /** Comment */
            comment?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** AddressRead */
        AddressRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * City Id
             * Format: uuid
             */
            city_id: string;
            /** Title */
            title: string | null;
            /** Street */
            street: string;
            /** House */
            house: string;
            /** Flat */
            flat: string | null;
            /** Entrance */
            entrance: string | null;
            /** Floor */
            floor: string | null;
            /** Intercom */
            intercom: string | null;
            /** Comment */
            comment: string | null;
            /** Is Default */
            is_default: boolean;
            /** Full Text */
            full_text: string;
        };
        /** Body_upload_api_v1_admin_uploads_post */
        Body_upload_api_v1_admin_uploads_post: {
            /** File */
            file: string;
        };
        /** CategoryAdminRead */
        CategoryAdminRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
            /** Image Url */
            image_url: string | null;
            /**
             * Dishes Count
             * @default 0
             */
            dishes_count: number;
        };
        /** CategoryPatch */
        CategoryPatch: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** CategoryWrite */
        CategoryWrite: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Image Url */
            image_url?: string | null;
        };
        /**
         * CheckoutLimits
         * @description Что гость может списать прямо сейчас — считаем на сервере, чтобы не спорить.
         */
        CheckoutLimits: {
            /** Points Balance */
            points_balance: number;
            /** Max Points To Spend */
            max_points_to_spend: number;
            /** Cashback Percent */
            cashback_percent: number;
        };
        /** CityRead */
        CityRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** CodeRequest */
        CodeRequest: {
            /**
             * Phone
             * @example +7 999 123-45-67
             */
            phone: string;
        };
        /** CodeRequestResult */
        CodeRequestResult: {
            /** Phone */
            phone: string;
            /** Resend After Seconds */
            resend_after_seconds: number;
            /** Debug Code */
            debug_code?: string | null;
        };
        /** CodeVerify */
        CodeVerify: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
        };
        /** DishAdminRead */
        DishAdminRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Composition */
            composition: string | null;
            /** Image Url */
            image_url: string | null;
            /** Price Kopecks */
            price_kopecks: number;
            /** Weight Grams */
            weight_grams: number | null;
            /** Volume Ml */
            volume_ml: number | null;
            /** Calories */
            calories: number | null;
            /** Is Active */
            is_active: boolean;
            /** Sort Order */
            sort_order: number;
        };
        /** DishPatch */
        DishPatch: {
            /** Category Id */
            category_id?: string | null;
            /** Name */
            name?: string | null;
            /** Price Kopecks */
            price_kopecks?: number | null;
            /** Description */
            description?: string | null;
            /** Composition */
            composition?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Weight Grams */
            weight_grams?: number | null;
            /** Volume Ml */
            volume_ml?: number | null;
            /** Calories */
            calories?: number | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** DishRead */
        DishRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Composition */
            composition: string | null;
            /** Image Url */
            image_url: string | null;
            /** Price Kopecks */
            price_kopecks: number;
            /** Weight Grams */
            weight_grams: number | null;
            /** Volume Ml */
            volume_ml: number | null;
            /** Calories */
            calories: number | null;
            /** Is Available */
            is_available: boolean;
        };
        /** DishWrite */
        DishWrite: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name */
            name: string;
            /** Price Kopecks */
            price_kopecks: number;
            /** Description */
            description?: string | null;
            /** Composition */
            composition?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Weight Grams */
            weight_grams?: number | null;
            /** Volume Ml */
            volume_ml?: number | null;
            /** Calories */
            calories?: number | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** GuestRead */
        GuestRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string;
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Birthday */
            birthday: string | null;
        };
        /** GuestUpdate */
        GuestUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Birthday */
            birthday?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoyaltyRead */
        LoyaltyRead: {
            /** Tier Code */
            tier_code: string;
            /** Tier Title */
            tier_title: string;
            /** Cashback Percent */
            cashback_percent: number;
            /** Points Balance */
            points_balance: number;
        };
        /** MenuCategoryRead */
        MenuCategoryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Image Url */
            image_url: string | null;
            /** Dishes */
            dishes: components["schemas"]["DishRead"][];
        };
        /** MenuRead */
        MenuRead: {
            /** Restaurant Id */
            restaurant_id: string | null;
            /** Categories */
            categories: components["schemas"]["MenuCategoryRead"][];
        };
        /** OrderCreate */
        OrderCreate: {
            /**
             * Restaurant Id
             * Format: uuid
             */
            restaurant_id: string;
            type: components["schemas"]["OrderType"];
            /** Items */
            items: components["schemas"]["OrderItemCreate"][];
            payment_method: components["schemas"]["PaymentMethod"];
            /** Address Text */
            address_text?: string | null;
            /** Address Latitude */
            address_latitude?: number | null;
            /** Address Longitude */
            address_longitude?: number | null;
            /** Delivery At */
            delivery_at?: string | null;
            /** Persons Count */
            persons_count?: number | null;
            /** Comment */
            comment?: string | null;
            /**
             * Points To Spend
             * @default 0
             */
            points_to_spend: number;
        };
        /** OrderItemCreate */
        OrderItemCreate: {
            /**
             * Dish Id
             * Format: uuid
             */
            dish_id: string;
            /** Quantity */
            quantity: number;
        };
        /** OrderItemRead */
        OrderItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Dish Id */
            dish_id: string | null;
            /** Name */
            name: string;
            /** Unit Price Kopecks */
            unit_price_kopecks: number;
            /** Quantity */
            quantity: number;
            /** Total Kopecks */
            total_kopecks: number;
        };
        /** OrderRead */
        OrderRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string;
            status: components["schemas"]["OrderStatus"];
            type: components["schemas"]["OrderType"];
            /**
             * Restaurant Id
             * Format: uuid
             */
            restaurant_id: string;
            /** Restaurant Name */
            restaurant_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivery At */
            delivery_at: string | null;
            /** Address Text */
            address_text: string | null;
            /** Comment */
            comment: string | null;
            /** Subtotal Kopecks */
            subtotal_kopecks: number;
            /** Delivery Kopecks */
            delivery_kopecks: number;
            /** Discount Kopecks */
            discount_kopecks: number;
            /** Total Kopecks */
            total_kopecks: number;
            /** Points Spent */
            points_spent: number;
            /** Points Earned */
            points_earned: number;
            payment_method: components["schemas"]["PaymentMethod"];
            payment_status: components["schemas"]["PaymentStatus"];
            /** Items */
            items: components["schemas"]["OrderItemRead"][];
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "created" | "paid" | "accepted" | "cooking" | "ready" | "delivering" | "completed" | "cancelled";
        /** OrderStatusWrite */
        OrderStatusWrite: {
            status: components["schemas"]["OrderStatus"];
            /** Cancel Reason */
            cancel_reason?: string | null;
        };
        /**
         * OrderType
         * @enum {string}
         */
        OrderType: "delivery" | "pickup";
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "online_card" | "online_sbp" | "cash_on_delivery" | "card_on_delivery";
        /**
         * PaymentStatus
         * @enum {string}
         */
        PaymentStatus: "not_required" | "pending" | "succeeded" | "cancelled" | "refunded";
        /** ProfileRead */
        ProfileRead: {
            guest: components["schemas"]["GuestRead"];
            loyalty: components["schemas"]["LoyaltyRead"];
        };
        /** PromotionAdminRead */
        PromotionAdminRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Label */
            label: string | null;
            /** Image Url */
            image_url: string | null;
            /** Restaurant Id */
            restaurant_id: string | null;
            /** Starts At */
            starts_at: string | null;
            /** Ends At */
            ends_at: string | null;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
            /** Restaurant Name */
            restaurant_name?: string | null;
        };
        /** PromotionPatch */
        PromotionPatch: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Label */
            label?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Restaurant Id */
            restaurant_id?: string | null;
            /** Starts At */
            starts_at?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** PromotionRead */
        PromotionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Label */
            label: string | null;
            /** Image Url */
            image_url: string | null;
            /** Restaurant Id */
            restaurant_id: string | null;
            /** Starts At */
            starts_at: string | null;
            /** Ends At */
            ends_at: string | null;
        };
        /** PromotionWrite */
        PromotionWrite: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Label */
            label?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Restaurant Id */
            restaurant_id?: string | null;
            /** Starts At */
            starts_at?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReservationCreate */
        ReservationCreate: {
            /**
             * Restaurant Id
             * Format: uuid
             */
            restaurant_id: string;
            /**
             * Reserved At
             * Format: date-time
             */
            reserved_at: string;
            /** Guests Count */
            guests_count: number;
            /** Comment */
            comment?: string | null;
            /** Contact Name */
            contact_name?: string | null;
        };
        /** ReservationRead */
        ReservationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ReservationStatus"];
            /**
             * Restaurant Id
             * Format: uuid
             */
            restaurant_id: string;
            /** Restaurant Name */
            restaurant_name: string;
            /**
             * Reserved At
             * Format: date-time
             */
            reserved_at: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Guests Count */
            guests_count: number;
            /** Comment */
            comment: string | null;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Phone */
            contact_phone: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReservationStatus
         * @enum {string}
         */
        ReservationStatus: "requested" | "confirmed" | "seated" | "completed" | "cancelled" | "no_show";
        /** ReservationStatusWrite */
        ReservationStatusWrite: {
            status: components["schemas"]["ReservationStatus"];
            /** Cancel Reason */
            cancel_reason?: string | null;
            /** Table Number */
            table_number?: string | null;
        };
        /** RestaurantRead */
        RestaurantRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * City Id
             * Format: uuid
             */
            city_id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Metro */
            metro: string | null;
            /** Phone */
            phone: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Has Delivery */
            has_delivery: boolean;
            /** Has Pickup */
            has_pickup: boolean;
            /** Has Dine In */
            has_dine_in: boolean;
            /** Delivery Price Kopecks */
            delivery_price_kopecks: number;
            /** Delivery Min Order Kopecks */
            delivery_min_order_kopecks: number;
            /** Free Delivery From Kopecks */
            free_delivery_from_kopecks: number | null;
            /** Image Url */
            image_url: string | null;
        };
        /** SessionRead */
        SessionRead: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            guest: components["schemas"]["GuestRead"];
            loyalty: components["schemas"]["LoyaltyRead"];
            /** Is New Guest */
            is_new_guest: boolean;
        };
        /**
         * SlotRead
         * @description Свободное время на выбранную дату, уже в часовом поясе ресторана.
         */
        SlotRead: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Label */
            label: string;
            /** Is Available */
            is_available: boolean;
        };
        /** StaffLogin */
        StaffLogin: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** StaffRead */
        StaffRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["StaffRole"];
        };
        /**
         * StaffRole
         * @enum {string}
         */
        StaffRole: "owner" | "manager";
        /** StaffSession */
        StaffSession: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            staff: components["schemas"]["StaffRead"];
        };
        /** StopListRead */
        StopListRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Restaurant Id
             * Format: uuid
             */
            restaurant_id: string;
            /** Restaurant Name */
            restaurant_name: string;
            /**
             * Dish Id
             * Format: uuid
             */
            dish_id: string;
            /** Dish Name */
            dish_name: string;
            /** Until */
            until: string | null;
            /** Comment */
            comment: string | null;
        };
        /** StopListWrite */
        StopListWrite: {
            /**
             * Restaurant Id
             * Format: uuid
             */
            restaurant_id: string;
            /**
             * Dish Id
             * Format: uuid
             */
            dish_id: string;
            /** Until */
            until?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_code_api_v1_auth_request_code_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeRequestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeVerify"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_addresses_api_v1_addresses_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_address_api_v1_addresses_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_address_api_v1_addresses__address_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                address_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cities_api_v1_cities_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_restaurants_api_v1_restaurants_get: {
        parameters: {
            query?: {
                city_id?: string | null;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_menu_api_v1_menu_get: {
        parameters: {
            query?: {
                restaurant_id?: string | null;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    limits_api_v1_orders_limits_get: {
        parameters: {
            query: {
                subtotal_kopecks: number;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutLimits"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_v1_orders_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_api_v1_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slots_api_v1_reservations_slots_get: {
        parameters: {
            query: {
                restaurant_id: string;
                date: string;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_v1_reservations_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_reservations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_reservations__reservation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                reservation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promotions_api_v1_promotions_get: {
        parameters: {
            query?: {
                restaurant_id?: string | null;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_admin_login_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_admin_uploads_post: {
        parameters: {
            query?: {
                folder?: string;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_admin_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_api_v1_admin_categories_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAdminRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_v1_admin_categories_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_admin_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_admin_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dishes_api_v1_admin_dishes_get: {
        parameters: {
            query?: {
                category_id?: string | null;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishAdminRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dish_api_v1_admin_dishes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dish_api_v1_admin_dishes__dish_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dish_api_v1_admin_dishes__dish_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_list_api_v1_admin_stop_list_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopListRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_stop_list_api_v1_admin_stop_list_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopListWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_stop_list_api_v1_admin_stop_list__entry_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_api_v1_admin_orders_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_order_status_api_v1_admin_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reservations_api_v1_admin_reservations_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_reservation_status_api_v1_admin_reservations__reservation_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                reservation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationStatusWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promotions_api_v1_admin_promotions_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionAdminRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_promotion_api_v1_admin_promotions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromotionWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_promotion_api_v1_admin_promotions__promotion_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                promotion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_promotion_api_v1_admin_promotions__promotion_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                promotion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromotionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
